import 'package:flutter/material.dart';
import '../widgets/programs_catrgory.dart';

const extraPrograms = <Program>[
  // Weight Loss
  Program(
    title: 'Beginner Fat Loss Starter',
    desc: 'A gentle introduction to calorie burning through walking and basic bodyweight moves.',
    days: '30 DAYS',
    level: 'LEVEL 1',
    category: ProgramCategory.weightLoss,
    icon: Icons.directions_walk,
    stat1: ProgramStat(Icons.timer_outlined, '20 min/day'),
    stat2: ProgramStat(Icons.local_fire_department, 'Step Focus'),
    dailyExercises: [
      WorkoutExercise(id: 'wls_1', name: 'Brisk Walk', target: 'Cardio', duration: '15 mins'),
      WorkoutExercise(id: 'wls_2', name: 'Bodyweight Squats', target: 'Legs', duration: '2 x 10 reps'),
      WorkoutExercise(id: 'wls_3', name: 'Wall Push-ups', target: 'Upper Body', duration: '2 x 10 reps'),
    ],
  ),
  Program(
    title: 'Home HIIT 20',
    desc: 'High-intensity interval training that fits into any schedule. No equipment needed.',
    days: '21 DAYS',
    level: 'LEVEL 3 • HIGH INTENSITY',
    category: ProgramCategory.weightLoss,
    icon: Icons.timer,
    highIntensity: true,
    stat1: ProgramStat(Icons.bolt, '20 min/day'),
    stat2: ProgramStat(Icons.local_fire_department, 'Max Burn'),
    dailyExercises: [
      WorkoutExercise(id: 'hiit_1', name: 'Jumping Jacks', target: 'Full Body', duration: '45 sec'),
      WorkoutExercise(id: 'hiit_2', name: 'Mountain Climbers', target: 'Core', duration: '45 sec'),
      WorkoutExercise(id: 'hiit_3', name: 'Burpees', target: 'Full Body', duration: '45 sec'),
      WorkoutExercise(id: 'hiit_4', name: 'High Knees', target: 'Cardio', duration: '45 sec'),
    ],
  ),
  Program(
    title: '10K Steps Walking Plan',
    desc: 'A structured plan to consistently hit your 10,000 steps goal every day.',
    days: '30 DAYS',
    level: 'ALL LEVELS',
    category: ProgramCategory.weightLoss,
    icon: Icons.directions_run,
    stat1: ProgramStat(Icons.straighten, '10k steps'),
    stat2: ProgramStat(Icons.calendar_today, 'Daily'),
    dailyExercises: [
      WorkoutExercise(id: 'step_1', name: 'Morning Walk', target: 'Base', duration: '3000 steps'),
      WorkoutExercise(id: 'step_2', name: 'Lunch Break Stroll', target: 'Base', duration: '2000 steps'),
      WorkoutExercise(id: 'step_3', name: 'Evening Power Walk', target: 'Cardio', duration: '5000 steps'),
    ],
  ),

  // Six-Pack Abs
  Program(
    title: 'Core Foundations',
    desc: 'Build the underlying strength needed for visible abs and better posture.',
    days: '14 DAYS',
    level: 'LEVEL 1',
    category: ProgramCategory.sixPack,
    icon: Icons.shield,
    stat1: ProgramStat(Icons.timer_outlined, '10 min/day'),
    stat2: ProgramStat(Icons.fitness_center, 'Stability'),
    dailyExercises: [
      WorkoutExercise(id: 'core_1', name: 'Plank', target: 'Core', duration: '3 x 30 sec'),
      WorkoutExercise(id: 'core_2', name: 'Dead Bug', target: 'Core', duration: '3 x 10 reps'),
      WorkoutExercise(id: 'core_3', name: 'Bird Dog', target: 'Back/Core', duration: '3 x 10 reps'),
    ],
  ),
  Program(
    title: 'Lower Abs & Obliques Sculpt',
    desc: 'Target the hard-to-reach areas of your midsection for a complete 360 sculpt.',
    days: '21 DAYS',
    level: 'LEVEL 2',
    category: ProgramCategory.sixPack,
    icon: Icons.architecture,
    stat1: ProgramStat(Icons.timer_outlined, '15 min/day'),
    stat2: ProgramStat(Icons.bolt, 'Targeted'),
    dailyExercises: [
      WorkoutExercise(id: 'sculpt_1', name: 'Leg Raises', target: 'Lower Abs', duration: '3 x 15 reps'),
      WorkoutExercise(id: 'sculpt_2', name: 'Russian Twists', target: 'Obliques', duration: '3 x 20 reps'),
      WorkoutExercise(id: 'sculpt_3', name: 'Heel Touches', target: 'Obliques', duration: '3 x 30 reps'),
    ],
  ),

  // Muscle & Strength
  Program(
    title: 'Full-Body Dumbbell Builder',
    desc: 'Transform your physique with just a pair of dumbbells. Perfect for home gyms.',
    days: '6 WEEKS',
    level: 'LEVEL 2',
    category: ProgramCategory.muscle,
    icon: Icons.fitness_center,
    stat1: ProgramStat(Icons.timer_outlined, '45 min/day'),
    stat2: ProgramStat(Icons.reorder, '3 days/week'),
    dailyExercises: [
      WorkoutExercise(id: 'db_1', name: 'DB Squats', target: 'Legs', duration: '3 x 12 reps'),
      WorkoutExercise(id: 'db_2', name: 'DB Chest Press', target: 'Chest', duration: '3 x 12 reps'),
      WorkoutExercise(id: 'db_3', name: 'DB Rows', target: 'Back', duration: '3 x 12 reps'),
      WorkoutExercise(id: 'db_4', name: 'DB Shoulder Press', target: 'Shoulders', duration: '3 x 12 reps'),
    ],
  ),
  Program(
    title: 'Gym Upper Body',
    desc: 'Classic gym-based hypertrophy for chest, back, shoulders, and arms.',
    days: '8 WEEKS',
    level: 'LEVEL 3',
    category: ProgramCategory.muscle,
    icon: Icons.fitness_center,
    stat1: ProgramStat(Icons.timer_outlined, '60 min/day'),
    stat2: ProgramStat(Icons.location_on, 'Gym Needed'),
    dailyExercises: [
      WorkoutExercise(id: 'upper_1', name: 'Bench Press', target: 'Chest', duration: '4 x 8 reps'),
      WorkoutExercise(id: 'upper_2', name: 'Lat Pulldowns', target: 'Back', duration: '4 x 10 reps'),
      WorkoutExercise(id: 'upper_3', name: 'Dumbbell Lateral Raises', target: 'Shoulders', duration: '3 x 15 reps'),
      WorkoutExercise(id: 'upper_4', name: 'Bicep Curls', target: 'Arms', duration: '3 x 12 reps'),
    ],
  ),
  Program(
    title: 'Gym Lower Body',
    desc: 'Heavy lifting for powerful legs and glutes using standard gym equipment.',
    days: '8 WEEKS',
    level: 'LEVEL 3',
    category: ProgramCategory.muscle,
    icon: Icons.fitness_center,
    stat1: ProgramStat(Icons.timer_outlined, '60 min/day'),
    stat2: ProgramStat(Icons.location_on, 'Gym Needed'),
    dailyExercises: [
      WorkoutExercise(id: 'lower_1', name: 'Barbell Squats', target: 'Legs', duration: '4 x 8 reps'),
      WorkoutExercise(id: 'lower_2', name: 'Leg Press', target: 'Legs', duration: '3 x 12 reps'),
      WorkoutExercise(id: 'lower_3', name: 'Romanian Deadlifts', target: 'Hamstrings', duration: '4 x 10 reps'),
      WorkoutExercise(id: 'lower_4', name: 'Calf Raises', target: 'Calves', duration: '4 x 20 reps'),
    ],
  ),
  Program(
    title: 'Bodyweight Strength Basics',
    desc: 'Master the fundamental movements to build a solid foundation of strength.',
    days: '4 WEEKS',
    level: 'LEVEL 1',
    category: ProgramCategory.muscle,
    icon: Icons.accessibility_new,
    stat1: ProgramStat(Icons.timer_outlined, '25 min/day'),
    stat2: ProgramStat(Icons.fitness_center, 'No Equipment'),
    dailyExercises: [
      WorkoutExercise(id: 'bw_1', name: 'Push-ups', target: 'Upper Body', duration: '3 x max reps'),
      WorkoutExercise(id: 'bw_2', name: 'Air Squats', target: 'Legs', duration: '3 x 20 reps'),
      WorkoutExercise(id: 'bw_3', name: 'Lunges', target: 'Legs', duration: '3 x 12 reps/side'),
      WorkoutExercise(id: 'bw_4', name: 'Plank', target: 'Core', duration: '3 x 45 sec'),
    ],
  ),

  // Endurance
  Program(
    title: 'Couch to 5K',
    desc: 'The world-famous plan to get you from the sofa to running 5km in 9 weeks.',
    days: '9 WEEKS',
    level: 'LEVEL 1',
    category: ProgramCategory.endurance,
    icon: Icons.directions_run,
    stat1: ProgramStat(Icons.timer_outlined, '30 min/day'),
    stat2: ProgramStat(Icons.reorder, '3 days/week'),
    dailyExercises: [
      WorkoutExercise(id: 'c25k_1', name: 'Warm-up Walk', target: 'Prep', duration: '5 mins'),
      WorkoutExercise(id: 'c25k_2', name: 'Run/Walk Intervals', target: 'Cardio', duration: '20 mins'),
      WorkoutExercise(id: 'c25k_3', name: 'Cool-down Walk', target: 'Recovery', duration: '5 mins'),
    ],
  ),
  Program(
    title: 'Interval Runner Speed Boost',
    desc: 'Specifically designed to improve your running pace through interval training.',
    days: '4 WEEKS',
    level: 'LEVEL 3',
    category: ProgramCategory.endurance,
    icon: Icons.speed,
    stat1: ProgramStat(Icons.timer_outlined, '40 min/day'),
    stat2: ProgramStat(Icons.bolt, 'High Intensity'),
    dailyExercises: [
      WorkoutExercise(id: 'speed_1', name: 'Jogging Warm-up', target: 'Prep', duration: '10 mins'),
      WorkoutExercise(id: 'speed_2', name: '400m Sprints', target: 'Speed', duration: '8 reps'),
      WorkoutExercise(id: 'speed_3', name: 'Recovery Walk', target: 'Recovery', duration: '2 min between reps'),
    ],
  ),

  // Mobility & Recovery
  Program(
    title: 'Morning Mobility Flow',
    desc: 'Wake up your joints and improve your range of motion for the day ahead.',
    days: '14 DAYS',
    level: 'ALL LEVELS',
    category: ProgramCategory.mobility,
    icon: Icons.wb_sunny,
    stat1: ProgramStat(Icons.timer_outlined, '10 min/day'),
    stat2: ProgramStat(Icons.self_improvement, 'Feel Great'),
    dailyExercises: [
      WorkoutExercise(id: 'mob_1', name: 'Cat-Cow', target: 'Spine', duration: '10 reps'),
      WorkoutExercise(id: 'mob_2', name: 'World Greatest Stretch', target: 'Full Body', duration: '5 reps/side'),
      WorkoutExercise(id: 'mob_3', name: 'Deep Squat Hold', target: 'Hips', duration: '60 sec'),
    ],
  ),
  Program(
    title: 'Desk Worker Recovery',
    desc: 'Reverse the negative effects of sitting all day with targeted stretches.',
    days: '21 DAYS',
    level: 'ALL LEVELS',
    category: ProgramCategory.mobility,
    icon: Icons.computer,
    stat1: ProgramStat(Icons.timer_outlined, '12 min/day'),
    stat2: ProgramStat(Icons.accessibility, 'Posture'),
    dailyExercises: [
      WorkoutExercise(id: 'desk_1', name: 'Neck Stretches', target: 'Neck', duration: '2 mins'),
      WorkoutExercise(id: 'desk_2', name: 'Chest Opener', target: 'Chest/Shoulders', duration: '2 mins'),
      WorkoutExercise(id: 'desk_3', name: 'Hip Flexor Stretch', target: 'Hips', duration: '2 mins/side'),
    ],
  ),
  Program(
    title: 'Post-Workout Recovery',
    desc: 'Cool down correctly to reduce soreness and improve muscle recovery.',
    days: 'ONGOING',
    level: 'ALL LEVELS',
    category: ProgramCategory.mobility,
    icon: Icons.airline_seat_recline_normal,
    stat1: ProgramStat(Icons.timer_outlined, '15 min'),
    stat2: ProgramStat(Icons.autorenew, 'Recovery'),
    dailyExercises: [
      WorkoutExercise(id: 'rec_1', name: 'Foam Rolling', target: 'Muscles', duration: '5 mins'),
      WorkoutExercise(id: 'rec_2', name: 'Static Stretching', target: 'Full Body', duration: '10 mins'),
    ],
  ),

];
